### ISSUE TITLE
Updating EMAIL history saving view & footer icons

### ISSUE THREAD

**Issue by maitri-vv** [Yashpatel191001/Infostic-Solution-Official-Website#1]
The form email section currently saves the previous history and it is visible, disabling it will keep privacy for the user.
![image](https://github.com/Yashpatel191001/Infostic-Solution-Official-Website/assets/87691594/b8bc1a2a-3561-4637-9cc9-774c2fec9ca7)

None of the icons on footer is clickable 
![image](https://github.com/Yashpatel191001/Infostic-Solution-Official-Website/assets/87691594/7d32ade3-9b28-4bc8-8f8c-d4c87a50ff91)

**Comment by maitri-vv** [comment]
@Yashpatel191001 i cannot access to raise a PR for the issue to solve it.

**Comment by Yashpatel191001** [comment]
Go ahead @maitri-vv

**Comment by maitri-vv** [comment]
![image](https://github.com/Yashpatel191001/Infostic-Solution-Official-Website/assets/87691594/fee7fecb-8bf7-4b7e-8808-fc1e46da65f4)
unable to raise a PR @Yashpatel191001

**Comment by Yashpatel191001** [comment]
First fork the repository and create a new branch in Forked Repository, and then make changes and create pull request
