### ISSUE TITLE
Modifying the tagline of Infostic-Solution-Official-Website

### ISSUE THREAD

**Issue by Sohoxic** [Yashpatel191001/Infostic-Solution-Official-Website#14]
Hello, I am Soham Sarkar, undergrad in PES University studying CSE, I would like to bring to your attention that the Tagline (Metus quisque ultricies vehicula proin, magna nullam.) for Infostic-Solution-Official-Website needs to be eye-catchy and hence needs to be modified. I would love to work on this, is you could assign me the same.

Thank You

**Comment by Yashpatel191001** [comment]
Go ahead @Sohoxic
