### ISSUE TITLE
Backend related

### ISSUE THREAD

**Issue by Uj293** [Yashpatel191001/Infostic-Solution-Official-Website#16]
I cloned the project in my localhost and i saw you are not using any backend for your website to store database as on clicking on signup button there is no page or message for successful sign up.
please assign this issue to me so that i can some backend related code to your website .
First we can start by merging a free AWS database, using MongoDB atlas for the testing phase.

I am good at Nodejs and mongodb so please assign this to me under GSSOC2023

**Comment by Yashpatel191001** [comment]
Go ahead @Uj293

**Comment by Uj293** [comment]
i will add a registration form page okk where a new user can enter the details and successfully create an account on the platform 
and i will also add validation on it okk like user with same email cannot create account twice.

**Comment by HadiaSamreen** [comment]
Hi @Uj293 I want to learn and contribute to backend too,Can we collaborate?

**Comment by Uj293** [comment]
okk @HadiaSamreen

**Comment by Uj293** [comment]
i am working on backend i already completed the whole backend part the only thing left is to commit changed in the project
