### ISSUE TITLE
Hosting website in vercel so that Changes made in the repository are reflected in real time.

### ISSUE THREAD

**Issue by Sohoxic** [Yashpatel191001/Infostic-Solution-Official-Website#20]
Hello I'm Soham Sarkar, I'd like to bring to your concern that the website does not reflect changes made in the repository in real time, so I suggest hosting the same through Vercel. 

P.S. Only the owner of this repository could do this task so I request the owner to take care of the same! Else the changes won't be reflected across the website!

**Comment by Yashpatel191001** [comment]
Sure, we'll check

**Comment by swarnade** [comment]
Thank U @Sohoxic For The Suggestion
