### ISSUE TITLE
I can add the hover effect in it. 

### ISSUE THREAD

**Issue by ashishdhiman0473** [Yashpatel191001/Infostic-Solution-Official-Website#37]
Please assign me the hovering task.

**Comment by Sohoxic** [comment]
Since there has been no progress with the issue assigned and also the issue doesn't specify exactly where the hover element is being applied, I would like to get assigned the issue and  work on the same!

**Comment by ashishdhiman0473** [comment]
> @Yashpatel191001 Since there has been no progress with the issue assigned and also the issue doesn't specify exactly where the hover element is being applied, I would like to get assigned the issue and work on the same!

You can see the progress now. 
Thank you 😊
