### ISSUE TITLE
Adding Favicon to Website

### ISSUE THREAD

**Issue by Prajwal0225** [Yashpatel191001/Infostic-Solution-Official-Website#40]
I wanted to bring to your attention an issue I noticed while using your website. Currently, the website does not have a favicon, which is the small icon that appears in the browser tab next to the page title.

Screenshot: 
![favicon is missing](https://github.com/Yashpatel191001/Infostic-Solution-Official-Website/assets/103810119/aea10db0-1878-402a-8d3a-984e60cabb33)

So, Can you please assign this issue to me? So, that I can start working on it.

**Comment by utkarshgupta04092003** [comment]
Hello,
Please assign me this issue, as my skills are aligned with this issue.

**Comment by Yashpatel191001** [comment]
Go ahead @utkarshgupta04092003

**Comment by Sohoxic** [comment]
If the task has not yet been completed, I'd like to contribute to the same and finish it as soon as possible @Yashpatel191001

**Comment by Prajwal0225** [comment]
Hello, @Yashpatel191001. I have a doubt regarding an issue I worked on. I made a pull request (PR) for this issue, and it got merged successfully. It even contains the GSSoC'23 label and level label. 

However, my PR is not being counted in the leaderboard. Do you have any idea why this might be happening?
