### ISSUE TITLE
I would like to add hover effect on card items.

### ISSUE THREAD

**Issue by Soulpurr** [Yashpatel191001/Infostic-Solution-Official-Website#45]
Adding a hover effect that will ease in or out the cards below in ss.
![Screenshot_2023-06-20-13-38-30-74_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Yashpatel191001/Infostic-Solution-Official-Website/assets/92094765/11691441-26c3-4eae-b2a2-806f2047adc5)
Pls assign this to me under gssoc23

**Comment by Yashpatel191001** [comment]
Go ahead @Soulpurr

**Comment by Soulpurr** [comment]
> Go ahead @Soulpurr

Hii can pls tell me what comes under level 1 2 3.How you guys decide which issue to label level 1 2 or 3?
