### ISSUE TITLE
Overflow in x direction in mobile

### ISSUE THREAD

**Issue by Soulpurr** [Yashpatel191001/Infostic-Solution-Official-Website#46]
I would like to fix overflow in x direction in mobile 

https://github.com/Yashpatel191001/Infostic-Solution-Official-Website/assets/92094765/c9f44975-2271-4d98-bb4d-5c6a8de6c83d
Pls assign this to me under gssoc23

**Comment by Yashpatel191001** [comment]
Go ahead @Soulpurr
