### ISSUE TITLE
[GSSOC'23]:  UI of footer and navbar

### ISSUE THREAD

**Issue by Naina047** [Yashpatel191001/Infostic-Solution-Official-Website#50]
In navbar, the title should be on left. and in footer socials should be on proper right.

I'm a GSSOC'23 contributor. please assign me this issue.

**Comment by Yashpatel191001** [comment]
@Naina047 Similar issue related to UI of footer is already there.

**Comment by Naina047** [comment]
But UI of navbar is also a issue. It should be on left and font color black is not so visible on blue it should be changed to white
