### ISSUE TITLE
improving UI of first div 

### ISSUE THREAD

**Issue by ich-tanishqa** [Yashpatel191001/Infostic-Solution-Official-Website#6]
We can improve the UI such that the subscribe button and that image can be seen in one div when someone opens the website.
Like the subscribe button and the rest of the text at one side with image on the other side.

**Comment by ich-tanishqa** [comment]
@Yashpatel191001 @swarnade I really want to work on this . Please assign me this issue

**Comment by Yashpatel191001** [comment]
Go ahead @ich-tanishqa
