### ISSUE TITLE
Adding Hover Effect to Cards in Plans and Pricing Section in Home Page

### ISSUE THREAD

**Issue by vanshika-singh518** [Yashpatel191001/Infostic-Solution-Official-Website#70]
The current plans and pricing section on the home page lacks visual interactivity, I'd like to add hover effects and make necessary improvements to enhance the section's interactivity.

Can you please assign me this to correct it under GSSOC'23. 
Thank you.
![image](https://github.com/Yashpatel191001/Infostic-Solution-Official-Website/assets/83200847/e8e59956-6578-426e-b8a3-76b4bddc5bfc)

**Comment by Yashpatel191001** [comment]
Go ahead @vanshika-singh518

**Comment by gurjeetsinghvirdee** [comment]
<img width="800" alt="Screenshot 2023-06-22 231740" src="https://github.com/Yashpatel191001/Infostic-Solution-Official-Website/assets/73753957/8532174c-f377-4488-9c48-22a46f75dcdb">

@vanshika-singh518
