### ISSUE TITLE
adding a signup page

### ISSUE THREAD

**Issue by Soulpurr** [Yashpatel191001/Infostic-Solution-Official-Website#73]
pls  assign this to me under gssoc23

**Comment by Yashpatel191001** [comment]
@Soulpurr Sign up page is already there, do you want to change or add anything?

**Comment by Soulpurr** [comment]
> @Soulpurr Sign up page is already there, do you want to change or add anything?

Adding some more fields like name and mobile number and also storing the data comming from sign up in localstorage untill the backend is created
