### ISSUE TITLE
consistent language across the website

### ISSUE THREAD

**Issue by shobhitexe** [Yashpatel191001/Infostic-Solution-Official-Website#75]
Some parts of the website is in english and some are in other langauge i guess the flow of language should be consistent throughout the website either in english or in other languages

![image](https://github.com/Yashpatel191001/Infostic-Solution-Official-Website/assets/29349136/82578241-386c-4af6-8963-f650ff4a997b)

![image](https://github.com/Yashpatel191001/Infostic-Solution-Official-Website/assets/29349136/7a637d02-d8b4-45bc-abc9-58ba8eee24b7)

**Comment by Yashpatel191001** [comment]
@shobhitexe Refer some websites that provided in README.md file for your reference
