### ISSUE TITLE
Non-functioning buttons in the Internship and services Section

### ISSUE THREAD

**Issue by Pro-18** [Yashpatel191001/Infostic-Solution-Official-Website#78]
In the Internship Section of our website, there are two buttons that are currently not working as intended. To address this issue, we propose the following solution:

Remove existing non-functioning buttons:
We will remove one of the non-functioning buttons to simplify the user interface and eliminate confusion.

Add an "Apply Now" button:
![Screenshot 2023-06-22 100803](https://github.com/Yashpatel191001/Infostic-Solution-Official-Website/assets/92087279/a5ba7906-946a-4d12-98bb-8cfdc16b9839)
![issue12](https://github.com/Yashpatel191001/Infostic-Solution-Official-Website/assets/92087279/b0149b38-6d59-4588-948a-7afe606a3b12)

**Comment by Yashpatel191001** [comment]
Go ahead @Pro-18
