### ISSUE TITLE
Fix alignment

### ISSUE THREAD

**Issue by divya-2910** [Yashpatel191001/Infostic-Solution-Official-Website#80]
The card and image are overlapping. Can I fix it under GSSOC'23
Also there is css of Services and internship pages included in (navbar.css) file. Can I create a new globals.css and shift the css there for better organization of files. 

![image](https://github.com/Yashpatel191001/Infostic-Solution-Official-Website/assets/113793606/68e4bf49-2d0b-4e9c-bd2f-0dece7b2bfc8)

Also in the internship page there should be space between buttons and the border
![image](https://github.com/Yashpatel191001/Infostic-Solution-Official-Website/assets/113793606/b352b3be-bc1c-4deb-9579-de2c2edc00a4)
I will fix these minor issues in 1 pr only

**Comment by Yashpatel191001** [comment]
Go ahead @divya-2910

**Comment by gurjeetsinghvirdee** [comment]
<img width="595" alt="image" src="https://github.com/Yashpatel191001/Infostic-Solution-Official-Website/assets/73753957/97b74710-685a-447f-abc7-a2062e99be1d">

@divya-2910

**Comment by divya-2910** [comment]
This isn't under GSSOC so I am closing it.

**Comment by Yashpatel191001** [comment]
@divya-2910 

Sorry for the inconvenience. Now this project is not a part of GSSoC'23, we've tried to contact program managers, but didn't get positive response. 

Don't worry, we've some good news for you.

As we promised, active contributors will get Certificate of Appreciation and LoR from Infostic Solution.

We've set some criteria for this.
- 3 PRs [Certificate of Appreciation]
- 5 or 5+ PRs [Certificate of Appreciation + LoR]

Why you should contribute in this project?
- Gain more experience in open-source
- Get Certificate of Appreciation and LoR
- Top contributors will get remote work opportunity with Infostic Solution

Remember that only top 100 contributors in GSSoC'23 will get certificate, remaining contributors will get nothing.

Note - We encourage you to continue your contribution in this project. It's not about only GSSoC, it's all about open-source journey and experience.

We're not forcing anyone to contribute, but if you're genuinely interested then you'll get all support, guidance and certificates for sure.
