### ISSUE TITLE
Fixing some bugs.

### ISSUE THREAD

**Issue by AdityaKumar2408** [Yashpatel191001/Infostic-Solution-Official-Website#87]
There are two improvements I would like to do:

1. I like to correct the button because it is different from all other button (it doesn't have any hover affect like all buttons)

![Screenshot (459)](https://github.com/Yashpatel191001/Infostic-Solution-Official-Website/assets/110921916/1c1d94ad-b88c-49ab-9b34-134239149ba2)

2. And also I would like to slightly shift the **Subscribe** button to right as it overlaps with text area of gmail while typing .

![Screenshot (460)](https://github.com/Yashpatel191001/Infostic-Solution-Official-Website/assets/110921916/6987e5b3-1d88-4c7d-ae19-4aac0d432be3)

**Comment by AdityaKumar2408** [comment]
Please assign this issue to me @Yashpatel191001

**Comment by Yashpatel191001** [comment]
Go ahead @AdityaKumar2408

**Comment by Soulpurr** [comment]
@AdityaKumar2408 this repo doesn't come under gssoc you pr will not be counted.check general of official discord.

**Comment by AdityaKumar2408** [comment]
@Soulpurr Thanks for the information you provided, I just confirmed your message with official discord chat.

**Comment by Soulpurr** [comment]
> @Soulpurr Thanks for the information you provided, I just confirmed your message with official discord chat.

Just do one thing help others on this repo by informing them too
